apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: "Filesystem"
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: fripiane/gift-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: root

        - name: db
          imagePullPolicy: IfNotPresent
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_DB
              value: GIFTProject
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: pg-script
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: 5432
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data
        - name: pg-script
          configMap:
            name: pg-script
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP