apiVersion: v1
kind: Pod
metadata:
  name: pg-data-pod
spec:
  volumes:
    - name: pg-data
      persistentVolumeClaim:
        claimName: pg-data
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - name: pg-data
          mountPath: /data
